name: Deploy backend

on: workflow_call

# These are example steps of what a backend pipeline might look like
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Build backend
        run: echo Building the backend \(unit tests are executed during the build\), creating and publishing a Docker image

  deploy-stage:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy backend to stage
        run: echo Deploying the backend to the staging environment
