name: Deploy frontend

on: workflow_call

# These are example steps of what a frontend pipeline might look like
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Test frontend
        run: echo Running unit tests and linters for the frontend, creating and publishing a Docker image

  deploy-stage:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Deploy frontend to stage
        run: echo Deploying the frontend to the staging environment
