name: TeamCity deployment

on: [ push, workflow_dispatch ]

jobs:
  # Builds the backend and deploys it to the staging environment
  backend:
    uses: ./.github/workflows/backend-stage.yml

  # Builds the frontend and deploys it to the staging environment
  frontend:
    uses: ./.github/workflows/frontend-stage.yml

  # Executes API automation tests
  automation-api:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: api

  # Executes UI automation tests
  automation-ui:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui

  # Executes UI automation tests in Firefox
  automation-ui-firefox:
    needs: [ backend, frontend ]
    uses: ./.github/workflows/automation.yml
    with:
      package: ui
      browser: firefox

  # Generates a report after all tests are completed
  report:
    needs: [ automation-api, automation-ui, automation-ui-firefox ]
    if: always()
    uses: ./.github/workflows/report.yml

  # Requires manual approval to deploy the backend and frontend to production
  # A production environment needs to be set up. Documentation: https://docs.github.com/en/actions/deployment/targeting-different-environments/using-environments-for-deployment#creating-an-environment
  # This step can be removed if you want production deployment to start automatically after all tests pass.
  # However, manual action here allows for additional reviews, as well as manual or performance testing if needed,
  # since deploying to production is a critical action.
  manual-prod-approval:
    needs: report
    if: success()
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Approve backend and frontend to production
        run: echo Approved to production

  # Deploys the backend and frontend to production
  deploy-prod:
    needs: manual-prod-approval
    uses: ./.github/workflows/deploy-prod.yml
