name: Allure report

on: workflow_call

jobs:
  allure-report:
    runs-on: ubuntu-latest
    steps:
      # Download all artifacts into a single directory to generate a unified report
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: allure-results
          merge-multiple: true

      # The following 3 steps handle saving Allure reports with history and publishing them to GitHub Pages.
      # Refer to the documentation: https://allurereport.org/docs/integrations-github/
      # Some steps must be performed manually in the repository settings to ensure correct publication.
      # Recommended steps for creating an empty `gh-pages` branch used for publishing reports:
      # https://gist.github.com/ramnathv/2227408?permalink_comment_id=2915143#gistcomment-2915143
      - name: Load test report history
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build test report
        uses: simple-elf/allure-report-action@v1.9
        with:
          gh_pages: gh-pages
          allure_history: allure-history
          allure_results: allure-results

      - name: Publish test report
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
